[package]
publish = false
name = "calculator"
edition = "2024"
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
evalexpr = "12.0"
wasm-bindgen = "0.2"

[profile.release]
lto = true
opt-level = 3
panic = "abort"
strip = true
