name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: rust-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            - uses: dtolnay/rust-toolchain@stable
              with:
                  target: wasm32-unknown-unknown
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - uses: jetli/wasm-bindgen-action@v0.2.0
              with:
                  version: "0.2.100"
            - run: npm install
            - run: npm run build
            - uses: cloudflare/wrangler-action@v3
              if: github.ref == 'refs/heads/main'
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  command: pages deploy --commit-dirty true
            - uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: build
